name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # यह लाइन GitHub को Node.js 24 इस्तेमाल करने के लिए मजबूर करेगी
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    runs-on: ubuntu-24.04 # हमने Ubuntu का सबसे लेटेस्ट वर्जन (24.04) चुना है

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good libffi-dev libssl-dev \
            libtool autoconf automake pkg-config cmake gettext
          
          python3 -m pip install --upgrade pip
          pip install --user --upgrade Cython==0.29.33 buildozer kivy kivymd

      - name: Build with Buildozer
        run: |
          # 'yes' कमांड अपने आप सारे एंड्रॉइड लाइसेंस स्वीकार कर लेगी
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MatrixApp-Final-APK
          path: bin/*.apk
