name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    # हमने वापस 22.04 कर दिया है क्योंकि यह ज्यादा स्टेबल है
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # हमने यहाँ से gstreamer हटा दिया है जो 100 एरर दे रहा था
          sudo apt-get install -y \
            build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev zlib1g-dev libffi-dev libssl-dev \
            libtool autoconf automake pkg-config cmake gettext libltdl-dev
          
          python3 -m pip install --upgrade pip
          # Cython का वर्जन फिक्स कर दिया है
          pip install --user --upgrade "Cython<3.0" buildozer kivy kivymd

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MatrixCalc-Fixed-Build
          path: bin/*.apk
          
